version: "3"
services:
  mcp-producer:
    platform: linux/amd64
    container_name: "mcp-producer"
    build: ./
    image: "ghcr.io/acedatacloud/mcp-producer:${BUILD_NUMBER}"
    ports:
      - "8000:8000"
